---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - get
- apiGroups:
  - reloader.akosrbn.io
  resources:
  - hotreloadprojects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - reloader.akosrbn.io
  resources:
  - hotreloadprojects/finalizers
  verbs:
  - update
- apiGroups:
  - reloader.akosrbn.io
  resources:
  - hotreloadprojects/status
  verbs:
  - get
  - patch
  - update
